### ISSUE TITLE
Heroku Error on Push

### ISSUE THREAD

**Issue by mbostrom82** [powdahound/s3browser#11]
when i do the last push command (git push heroku master) i get this:

"No default language could be detected for this app."

I tried and set the build pack to php... but get an error like this:

heroku buildpacks:set heroku/php

then when i try to push i get this:

Counting objects: 3, done.
Writing objects: 100% (3/3), 217 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Failed to detect set buildpack https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/php.tgz
remote: More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to s3-file-browser.
remote:

**Comment by mbostrom82** [comment]
no where in the instructions mentioned this but this seemed to help me:

To switch from SSH Git to HTTP Git, run heroku git:remote in the directory holding your local Git repository. The CLI will override the heroku Git remote to use the HTTP protocol.

**Comment by powdahound** [comment]
Good to know. So this issue is resolved?
