### ISSUE TITLE
PermanentRedirect

### ISSUE THREAD

**Issue by zystem** [powdahound/s3browser#18]
S3::getBucket(): [PermanentRedirect] The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. in /app/www/libs/s3-php/S3.php on line 374

**Comment by powdahound** [comment]
Try setting the `s3-endpoint` config option as added in #8 and set the value to the proper endpoint as explained in https://stackoverflow.com/a/31939486/121515. 🤞
