### ISSUE TITLE
Leaf File Access

### ISSUE THREAD

**Issue by duane-unitive** [powdahound/s3browser#9]
When I browse to a leaf file and try to download the file, I receive 

```
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>19D9A08618EBEC18</RequestId>
  <HostId>
    qKjDBMmPVQkE4G0B8Qin8s6sZ3EbAa2u3gt0gfxiZ9zFtdEnqO8CjBBsw4M4EZdJ
  </HostId>
</Error>
```

When I use the same authentication information (access key id and secret access key) with the AWS CLI the files can be downloaded. In fact, I use the same IAM user to upload the files using the AWS CLI.

How do I download files with the s3browser?

**Comment by duane-unitive** [comment]
I see that if the file is marked as "public" then the file can be downloaded. I don't want these files to be public. They should only accessible through the S3 IAM user authentication.

**Comment by powdahound** [comment]
Support for making signed request URLs would be nice to have for sure. It'd probably take a bit of refactoring given the extremely dumb logic of this app currently. The code is very old and a bit embarrassing to me these days. :)

**Comment by duane-unitive** [comment]
Thank you, but I'm not really interested in signed request URLs. I have added an authentication interface for the application. I would just like to be able to download items using the AWS IAM authenticated secret. The same authentication works with AWS CLI, but I need an web interface. 

Thanks.

**Comment by powdahound** [comment]
Do you know if S3 allows those credentials to be provided in the URL? If so, can you link the docs for that? It's not something I've seen before but I have not looked into that stuff for a long time. Its possible that the CLI tool just uses the credentials to generate a single-use signed URL.

**Comment by powdahound** [comment]
Took a quick look myself and it looks like you can pass an `Authorization` header for access, but that's not something we can specify in an HTML link.

**Comment by duane-unitive** [comment]
Thanks, I'll look into this, perhaps. 

I was also trying to work out how leaf nodes were downloaded at all? I have not been able to work out how the file is transferred by the browser through PHP with the link in the UI.

**Comment by powdahound** [comment]
The files don't pass through the PHP code at all. Since they are public we just link directly to them.

**Comment by duane-unitive** [comment]
That explains why authorization doesn't work. 😄 The files are likely accessible through the S3 connection, but would then have to be transferred to the browser. 

That might be something I can do.
